### PR TITLE
Upgrade to Sphinx 6

### PR DESCRIPTION
**Pull request by othercorey**

### CODE REVIEW

**Comment by othercorey** [comment]
Looks like this fails building plugins although docs built successfully.

**Comment by LordSimal** [comment]
do we wanna tackle the stan issues here as well or in a separate PR?

**Comment by othercorey** [comment]
> do we wanna tackle the stan issues here as well or in a separate PR?

Here is fine. Thanks for looking into it.

**Comment by LordSimal** [comment]
Thanks for taking care of the sphinx upgrade 😁

**Comment by othercorey** [comment]
Bumped up to sphinx 7 with the new phpdomain package.

**Pull request merged**
